/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF, Html, Grid } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useSpring, animated } from '@react-spring/three'


export default function Model({ exploded, ...props }) {
  const { nodes, materials } = useGLTF('/f1.glb.glb')
  const [activePart, setActivePart] = useState(null)

  // --- REFS ---
  const frontLeft = useRef()
  const frontRight = useRef()
  const rearLeft = useRef()
  const rearRight = useRef()

  // --- TOGGLE LOGIC ---
  const togglePart = (e, name) => {
    e.stopPropagation()
    if (!exploded) return
    setActivePart(activePart === name ? null : name)
  }
  // --- ANIMATION LOOP ---
  useFrame((state, delta) => {
    if (!exploded) {
      const speed = 10

      // Spin Wheels
      if(frontLeft.current) frontLeft.current.rotation.x += delta * speed
      if(frontRight.current) frontRight.current.rotation.x += delta * speed
      if(rearLeft.current) rearLeft.current.rotation.x += delta * speed
      if(rearRight.current) rearRight.current.rotation.x += delta * speed
    }
  })

  // --- SPRINGS ---
  const springs = useSpring({
    frontRight: exploded ? [-2.5, 0.366, 1.801] : [-0.805, 0.366, 1.801],
    rearLeft: exploded ? [2.5, 0.359, -1.801] : [0.782, 0.359, -1.801],
    rearRight: exploded ? [-2.5, 0.359, -1.801] : [-0.782, 0.359, -1.801],
    frontWheelLeft: exploded ? [2.5, 0.366, 1.801] : [0.805, 0.366, 1.801],
    frontWing: exploded ? [0, 0.5, 1.5] : [0, 0, 0],
    frontNose: exploded ? [0, 0.5, 2] : [0, 0, 0],
    rearWing: exploded ? [0, 1.5, -1.5] : [0, 0, 0],
    bodyShell: exploded ? [0, 1.5, 0] : [0, 0, 0],
    steeringWheel: exploded ? [0, 3, 0.805] : [0, 0.601, 0.805],
    config: { mass: 1, tension: 120, friction: 20 }
  })

  return (
    <group {...props} dispose={null}>

      <animated.group
        position={springs.frontWing}
        onClick={(e) => togglePart(e, 'Front Wing')}
        onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}
      >
        {exploded && activePart !== 'Front Wing' && (
          <Html position={[0, 0.8, 2.2]} center distanceFactor={10} zIndexRange={[100, 0]}>
            <div className="permanent-label">
              <h4>Front Wing</h4>
              <p>Downforce generator</p>
            </div>
          </Html>
        )}
        {exploded && activePart === 'Front Wing' && (
          <Html position={[0, 1.5, 3.5]} center distanceFactor={10} zIndexRange={[100, 0]}>
            <div className="label">
              <h3>Front Wing & Nose</h3>
              <p>Five-element aerofoil with the titanium nose cone bonded to the main plane, guiding airflow to the floor and cooling inlets.</p>
            </div>
          </Html>
        )}
         <mesh geometry={nodes.Object_86.geometry} material={materials.mercedes_carbon3} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.mercedes_carbon3} position={[-0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.mercedes_carbon3} position={[0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.mercedes_carbon1} position={[0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.mercedes_carbon1} position={[-0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.mercedes_carbon1} position={[-0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.mercedes_carbon1} position={[0.94, 0.344, 2.528]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.mercedes_paint} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.mercedes_detail} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.mercedes_carbon1} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.mercedes_carbon3} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.mercedes_paint} position={[0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.mercedes_detail} position={[0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.mercedes_paint} position={[-0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.mercedes_detail} position={[-0.577, 0.284, 2.46]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_609.geometry} material={materials.generics} />
            <mesh geometry={nodes.Object_77.geometry} material={materials.mercedes_paint} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_618.geometry} material={materials.generics} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.generics} position={[0, 1.128, -0.051]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.mercedes_detail} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
          
         
        
        
     
        
      <mesh geometry={nodes.Object_14.geometry} material={materials.generics} position={[0, 0.257, 2.711]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_615.geometry} material={materials.mercedes_decal} position={[0, 0.001, 0]} scale={100.001} />
      <mesh geometry={nodes.Object_396.geometry} material={materials.mercedes_decal} position={[0.001, 0, 0]} scale={100} />
      <mesh geometry={nodes.Object_408.geometry} material={materials.mercedes_decal} position={[-0.001, 0, 0]} scale={100} />
     <mesh geometry={nodes.Object_83.geometry} material={materials.mercedes_carbon1} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
      </animated.group>
 <mesh geometry={nodes.Object_195.geometry} material={materials.mercedes_carbon3} position={[-0.159, -0.02, 0]} />
   
   
   <mesh geometry={nodes.Object_127.geometry} material={materials.mercedes_carbon3} />
<mesh geometry={nodes.Object_405.geometry} material={materials.mercedes_decal_2} position={[0, 0.001, 0]} scale={100} />
 <mesh geometry={nodes.Object_411.geometry} material={materials.mercedes_decal} position={[0, 0.001, 0]} scale={100} />
<mesh geometry={nodes.Object_402.geometry} material={materials.mercedes_decal} position={[0, 0, 0.001]} />
<mesh geometry={nodes.Object_399.geometry} material={materials.mercedes_decal} position={[0, 0, 0.001]} scale={100} />







        <animated.group position={springs.bodyShell} onClick={(e) => togglePart(e, 'Body Shell')}
      onPointerOver={() => document.body.style.cursor = 'pointer'}
  onPointerOut={() => document.body.style.cursor = 'auto'}>
         {exploded && activePart !== 'Body Shell' && (
            <Html position={[1.5, 1, 0]} center distanceFactor={10} zIndexRange={[100, 0]}>
              <div className="permanent-label">
                <h4>Sidepods</h4>
                <p>Cooling & aerodynamics</p>
              </div>
            </Html>
         )}
         {exploded && activePart === 'Body Shell' && (

            <Html position={[2, -0.7, 0]} center distanceFactor={10} zIndexRange={[100, 0]}>
              <div className="label">
                <h3>Sidepods & Engine Cover</h3>
                <p>Carbon fiber bodywork housing the Power Unit and radiators, integrated with the titanium Halo safety structure.</p>
              </div>
            </Html>
         )}
         <group position={[0, 0.466, 0.269]}>
        <mesh geometry={nodes.Object_579.geometry} material={materials.mercedes_decal} position={[0.001, 0, 0]} />
        <mesh geometry={nodes.Object_582.geometry} material={materials.mercedes_decal} position={[-0.001, 0, 0]} />
        <mesh geometry={nodes.Object_594.geometry} material={materials.mercedes_decal} position={[0, 0.001, 0]} />
        <mesh geometry={nodes.Object_540.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_543.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_546.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_549.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_552.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_555.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_558.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_561.geometry} material={materials.generics} />
        <mesh geometry={nodes.Object_564.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_567.geometry} material={materials.mercedes_carbon1} />

        <mesh geometry={nodes.Object_570.geometry} material={materials.mercedes_paint} />
        
        <mesh geometry={nodes.Object_573.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_576.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_585.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_588.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_591.geometry} material={materials['erslight.001']} />
        <mesh geometry={nodes.Object_597.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_600.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_603.geometry} material={materials.generics} />
        <mesh geometry={nodes.Object_606.geometry} material={materials.mercedes_paint} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.mercedes_detail} position={[0, 0.31, -1.815]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.mercedes_paint} position={[0, 0.381, 0.85]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_612.geometry} material={materials.mercedes_carbon1} />
      </group>
       
        
 <mesh geometry={nodes.Object_32.geometry} material={materials.mercedes_carbon1} position={[0, 0.812, 0.996]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.mercedes_paint} position={[0, 0.733, 0.453]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.mercedes_paint} position={[0, 0.812, 0.996]} rotation={[Math.PI / 2, 0, 0]} />
             <mesh geometry={nodes.Object_133.geometry} material={materials.mercedes_decal} />
          <mesh geometry={nodes.Object_218.geometry} material={materials.mirror} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.mirror} />
    <mesh geometry={nodes.Object_26.geometry} material={materials.generics} position={[0, 0.519, 1.909]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Object_98.geometry} material={materials.mercedes_detail} position={[0, 1.128, -0.051]} rotation={[Math.PI / 2, 0, 0]} />
        </animated.group>

        <group
          position={[0, 0.55, -0.3]}
          onClick={(e) => togglePart(e, 'Engine')}
          onPointerOver={() => document.body.style.cursor = 'pointer'}
          onPointerOut={() => document.body.style.cursor = 'auto'}
        >
          {exploded && activePart !== 'Engine' && (
            <Html position={[0, 1.3, 0]} center distanceFactor={9} zIndexRange={[100, 0]}>
              <div className="permanent-label">
                <h4>Power Unit</h4>
                <p>V6 Turbo Hybrid</p>
              </div>
            </Html>
          )}
          {exploded && activePart === 'Engine' && (
            <Html position={[-2, 0.8, 0]} center distanceFactor={9} zIndexRange={[100, 0]}>
              <div className="label">
                <h3>Power Unit</h3>
                <p>Mercedes-AMG V6 turbo hybrid with split turbo layout, MGU-K/ MGU-H harvesters, and battery pack integrated beneath the survival cell.</p>
              </div>
            </Html>
          )}
          <mesh>
            <boxGeometry args={[1.4, 0.7, 1.1]} />
            <meshBasicMaterial transparent opacity={0} depthWrite={false} depthTest={false} />
          </mesh>
        </group>



        <mesh geometry={nodes.Object_23.geometry} material={materials.generics} />
          <mesh geometry={nodes.Object_530.geometry} material={materials.cockpit_metal} />
<mesh geometry={nodes.Object_524.geometry} material={materials.cockpit_foam} />



     
     
     
   <mesh geometry={nodes.Object_527.geometry} material={materials.cockpit} />

      <mesh geometry={nodes.Object_89.geometry} material={materials.mercedes_detail} position={[0, 0.363, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.generics} position={[0, 0.363, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.mercedes_carbon1} position={[0, 1.128, -0.051]} rotation={[Math.PI / 2, 0, 0]} />

   
      <mesh geometry={nodes.Object_104.geometry} material={materials.mercedes_number} position={[0, -2.636, 0]} />
      <animated.group position={ springs.frontWheelLeft} rotation={[Math.PI / 2, 0.035, 0]} onClick={(e) => togglePart(e, 'Front Tire')}
      onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}>
        
      {exploded && activePart !== 'Front Tire' && (
        <Html position={[0.8, 0, 0]} center distanceFactor={8}>
          <div className="permanent-label">
            <h4>Front Left</h4>
            <p>Pirelli P-Zero</p>
          </div>
        </Html>
      )}

      {exploded && activePart === 'Front Tire' && (
    <Html position={[1.5, 0, 0]} center distanceFactor={8}>
      <div className="annotation">
        <h4>Front Tires - Soft Compound</h4>
        <p style={{fontSize: '10px'}}>Pirelli P-Zero tires with advanced silica tread compound, multi-layer construction with aramid belts, and grooved tread pattern for maximum grip. Front tires prioritize steering response and braking performance.</p>
      </div>
    </Html>
  )}
      
      <group ref={frontLeft}>
        <mesh geometry={nodes.Object_114.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_117.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.mercedes_wheel_hub} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.mercedes_wheel_hub} />
        </group>
      </animated.group>
      <group position={[0.805, 0.366, 1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_136.geometry} material={materials.mercedes_paint_alpha} position={[-0.001, 0, -0.001]} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.mercedes_carbon1} />
  
        <mesh geometry={nodes.Object_130.geometry} material={materials.mercedes_carbon1} />
     
      </group>
      <group position={[-0.805, 0.366, 1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_152.geometry} material={materials.mercedes_paint_alpha} position={[0.001, 0, -0.001]} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.mercedes_decal} />
      </group>
      <animated.group position={springs.frontRight} rotation={[Math.PI / 2, -0.035, 0] } onClick={(e) => togglePart(e, 'Front Tire')} onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}>
          {exploded && activePart !== 'Front Tire' && (
            <Html position={[-0.8, 0, 0]} center distanceFactor={8}>
              <div className="permanent-label">
                <h4>Front Right</h4>
                <p>Pirelli P-Zero</p>
              </div>
            </Html>
          )}
          {exploded && activePart === 'Front Tire' && (
    <Html position={[-1.5, 0, 0]} center distanceFactor={8}>
      <div className="annotation">
        <h4>Soft Compound</h4>
        <p style={{fontSize: '10px'}}>Pirelli P-Zero tires with advanced silica tread compound, multi-layer construction with aramid belts, and grooved tread pattern for maximum grip. Front tires prioritize steering response and braking performance.</p>
      </div>
    </Html>
  )}
       <group ref={frontRight}>
        <mesh geometry={nodes.Object_162.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_165.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_156.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_168.geometry} material={materials.mercedes_wheel_hub} />
        </group>
      </animated.group>
      <animated.group ref={rearRight} position={springs.rearRight} rotation={[Math.PI / 2, 0, 0]} onClick={(e) => togglePart(e, 'Back Tire')}
            onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}>
           {exploded && activePart !== 'Back Tire' && (
             <Html position={[-0.8, 0, 0.2]} center distanceFactor={8}>
               <div className="permanent-label">
                 <h4>Rear Right</h4>
                 <p>Pirelli P-Zero</p>
               </div>
             </Html>
           )}
           {exploded && activePart === 'Back Tire' && (
          <Html position={[-1.5, 0, 0.2]} center distanceFactor={8}>
      <div className="annotation">
        <h4>Rear Tires - Soft Compound</h4>
        <p style={{fontSize: '10px'}}>Pirelli P-Zero tires optimized for rear axle traction and acceleration. Specialized compound provides excellent grip for power delivery while maintaining durability through high-speed corners.</p>
      </div>
    </Html>
           )}

        <mesh geometry={nodes.Object_178.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_181.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_172.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_175.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_184.geometry} material={materials.mercedes_wheel_hub} />
      </animated.group>
      <group position={[-0.782, 0.359, -1.801]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_188.geometry} material={materials.mercedes_carbon3} position={[0.16, -0.02, 0]} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.mercedes_carbon1} position={[0.16, -0.02, 0]} />
      </group>
      <group position={[0.782, 0.359, -1.801]} rotation={[Math.PI / 2, 0, 0]}>
     
        <mesh geometry={nodes.Object_198.geometry} material={materials.mercedes_carbon1} position={[-0.159, -0.02, 0]} />
      </group>
      <animated.group ref={rearLeft} position={springs.rearLeft} rotation={[Math.PI / 2, 0, 0]} onClick={(e) => togglePart(e, 'Back Tire')}
            onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}>
           {exploded && activePart !== 'Back Tire' && (
             <Html position={[0.8, 0, 0.2]} center distanceFactor={8}>
               <div className="permanent-label">
                 <h4>Rear Left</h4>
                 <p>Pirelli P-Zero</p>
               </div>
             </Html>
           )}
           {exploded && activePart === 'Back Tire' && (
          <Html position={[1.5, 0, 0.2]} center distanceFactor={8}>
      <div className="annotation">
        <h4>Rear Tires - Soft Compound</h4>
        <p style={{fontSize: '10px'}}>Pirelli P-Zero tires optimized for rear axle traction and acceleration. Specialized compound provides excellent grip for power delivery while maintaining durability through high-speed corners.</p>
      </div>
    </Html>
           )}
        <mesh geometry={nodes.Object_208.geometry} material={materials['TIRE_SIDES.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_211.geometry} material={materials['TIRE_TREAD.001']} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_202.geometry} material={materials.discs} />
        <mesh geometry={nodes.Object_205.geometry} material={materials.mercedes_wheel_hub} />
        <mesh geometry={nodes.Object_214.geometry} material={materials.mercedes_wheel_hub} />
      </animated.group>
      <animated.group position={[0.446, 0.723, 0.82]} rotation={[Math.PI / 2, 0, 0]}>
        
        <mesh geometry={nodes.Object_221.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_224.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_227.geometry} material={materials.mercedes_carbon1} />
        <mesh geometry={nodes.Object_230.geometry} material={materials.mercedes_carbon3} />
      </animated.group>
      <group position={[-0.446, 0.723, 0.82]} rotation={[Math.PI / 2, 0, 0]}>
        
        <mesh geometry={nodes.Object_237.geometry} material={materials.mercedes_paint} />
        <mesh geometry={nodes.Object_240.geometry} material={materials.mercedes_detail} />
        <mesh geometry={nodes.Object_243.geometry} material={materials.mercedes_carbon1} />
   
      </group>
      <animated.group position={springs.steeringWheel} rotation={[1.605, 0, 0]}onClick={(e) => togglePart(e, 'Steering Wheel')}
            onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}>
           {exploded && activePart !== 'Steering Wheel' && (
             <Html position={[0, 2.5, 0]} center distanceFactor={8}>
               <div className="permanent-label">
                 <h4>Steering Wheel</h4>
                 <p>Control unit</p>
               </div>
             </Html>
           )}
           {exploded && activePart === 'Steering Wheel' && (
          <Html position={[0, 0.5, -0.3]} center distanceFactor={8}>
      <div className="annotation">
        <h4>Steering Wheel</h4>
        <p style={{fontSize: '10px'}}>Carbon fiber control unit with LCD telemetry display, differential settings, and brake balance adjusters.</p>
      </div>
    </Html>
           )}
        <mesh geometry={nodes.Object_250.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.004]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_253.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.007]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_256.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.027]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_259.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.029]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_262.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.032]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_265.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.034]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_268.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.036]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_271.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.038]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_274.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.041]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_277.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.043]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_280.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.045]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_283.geometry} material={materials['erslight.001']} position={[-0.043, -0.071, -0.048]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_286.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.009]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_289.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.011]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_292.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.013]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_295.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.016]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_298.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.018]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_301.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.02]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_304.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.023]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_307.geometry} material={materials['erslight.001']} position={[-0.043, -0.072, -0.025]} rotation={[0.014, 0, 0]} scale={[0.529, 0, 1.454]} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.material} position={[0.002, -0.065, -0.014]} rotation={[-Math.PI / 2, 0, 0]} scale={1.01} />
        <mesh geometry={nodes.Object_313.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.065]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_316.geometry} material={materials.CLEARLED} position={[-0.002, -0.014, -0.001]} scale={1.156} />
        <mesh geometry={nodes.Object_319.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_322.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_325.geometry} material={materials.CLEARLED} position={[0, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_328.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_331.geometry} material={materials.CLEARLED} position={[0.006, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_334.geometry} material={materials.CLEARLED} position={[-0.002, -0.013, -0.001]} scale={1.156} />
        <mesh geometry={nodes.Object_337.geometry} material={materials.sw_rotaries} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_340.geometry} material={materials.SW_BLACK} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_343.geometry} material={materials.SW_DECALS} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_346.geometry} material={materials.SW_HANDLES} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_349.geometry} material={materials.SW_MAIN} position={[0, -0.073, -0.067]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_352.geometry} material={materials.mercedes_decal} position={[0, -0.073, -0.068]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_355.geometry} material={materials.SW_METAL} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_358.geometry} material={materials.SW_MONITOR_BACK} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_361.geometry} material={materials.SW_PADDLES} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_364.geometry} material={materials.SW_PLASTIC} position={[0, -0.837, 0.446]} rotation={[0.087, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_367.geometry} material={materials.material_25} position={[0.053, -0.046, -0.09]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.008, 0.678, 0.023]} />
        <mesh geometry={nodes.Object_370.geometry} material={materials.TAG_DRS_ON} position={[0.036, -0.07, -0.063]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_373.geometry} material={materials.CLEARLED_PRE} position={[0.036, -0.07, -0.063]} scale={[1.348, 1.089, 1.348]} />
        <mesh geometry={nodes.Object_376.geometry} material={materials.CLEARLED} position={[0.019, -0.07, -0.064]} scale={[1.348, 1.089, 1.348]} />
      </animated.group>
    
      <mesh geometry={nodes.Object_385.geometry} material={materials.driver_color} position={[0, -2.639, 0]} scale={[100.126, 100.042, 100.042]} />
      <group position={[0, 0.657, -1.778]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_389.geometry} material={materials.rear_light} />
        <mesh geometry={nodes.Object_392.geometry} material={materials.generics} />
      </group>
      <group position={[0.19, 0.54, 1.683]} rotation={[-0.281, -0.112, -0.052]}>
        <mesh geometry={nodes.Object_415.geometry} material={materials.mercedes_carbon3} position={[0.021, 0.001, 0.173]} rotation={[1.85, 0.019, -0.122]} />
        <mesh geometry={nodes.Object_418.geometry} material={materials.mercedes_carbon1} position={[0.021, 0.001, 0.173]} rotation={[1.85, 0.019, -0.122]} />
        <mesh geometry={nodes.Object_421.geometry} material={materials.mercedes_carbon1} position={[0.037, -0.001, -0.125]} rotation={[1.85, 0.019, -0.122]} />
      </group>
      <group position={[-0.19, 0.54, 1.683]} rotation={[2.861, -0.112, 3.089]}>
        <mesh geometry={nodes.Object_425.geometry} material={materials.mercedes_carbon3} position={[0.021, 0.001, -0.173]} rotation={[1.292, 0.019, -3.019]} />
        <mesh geometry={nodes.Object_428.geometry} material={materials.mercedes_carbon1} position={[0.021, 0.001, -0.173]} rotation={[1.292, 0.019, -3.019]} />
        <mesh geometry={nodes.Object_431.geometry} material={materials.mercedes_carbon1} position={[0.037, -0.001, 0.125]} rotation={[1.292, 0.019, -3.019]} />
      </group>
      <group position={[0.31, 0.554, 1.713]} rotation={[0, -0.07, -0.422]}>
        <mesh geometry={nodes.Object_435.geometry} material={materials.mercedes_carbon3} position={[-0.017, 0, 0.007]} rotation={[Math.PI / 2, 0.422, -0.07]} />
        <mesh geometry={nodes.Object_438.geometry} material={materials.mercedes_carbon1} position={[-0.017, 0, 0.007]} rotation={[Math.PI / 2, 0.422, -0.07]} />
      </group>
      <group position={[-0.31, 0.554, 1.713]} rotation={[Math.PI, -0.07, 2.719]}>
        <mesh geometry={nodes.Object_442.geometry} material={materials.mercedes_carbon3} position={[-0.017, 0, -0.007]} rotation={[Math.PI / 2, 0.422, -3.072]} />
        <mesh geometry={nodes.Object_445.geometry} material={materials.mercedes_carbon1} position={[-0.017, 0, -0.007]} rotation={[Math.PI / 2, 0.422, -3.072]} />
      </group>
      <group position={[0.239, 0.379, 1.737]} rotation={[-0.123, 0.012, -0.099]}>
        <mesh geometry={nodes.Object_449.geometry} material={materials.mercedes_carbon3} position={[-0.014, -0.008, 0.123]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_452.geometry} material={materials.mercedes_carbon1} position={[-0.014, -0.008, 0.123]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_455.geometry} material={materials.mercedes_carbon1} position={[-0.03, 0.006, -0.256]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_458.geometry} material={materials.mercedes_carbon3} position={[-0.02, -0.006, 0.219]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_461.geometry} material={materials.mercedes_carbon1} position={[-0.02, -0.006, 0.219]} rotation={[1.695, 0.099, 0]} />
        <mesh geometry={nodes.Object_464.geometry} material={materials.mercedes_carbon3} position={[-0.054, -0.007, 0.125]} rotation={[1.695, 0.099, 0]} />
      </group>
      <group position={[-0.239, 0.379, 1.737]} rotation={[3.018, 0.012, 3.043]}>
        <mesh geometry={nodes.Object_468.geometry} material={materials.mercedes_carbon3} position={[-0.014, -0.008, -0.123]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_471.geometry} material={materials.mercedes_carbon1} position={[-0.014, -0.008, -0.123]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_474.geometry} material={materials.mercedes_carbon1} position={[-0.03, 0.006, 0.256]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_477.geometry} material={materials.mercedes_carbon3} position={[-0.02, -0.006, -0.219]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_480.geometry} material={materials.mercedes_carbon1} position={[-0.02, -0.006, -0.219]} rotation={[1.447, 0.099, Math.PI]} />
        <mesh geometry={nodes.Object_483.geometry} material={materials.mercedes_carbon3} position={[-0.054, -0.007, -0.125]} rotation={[1.447, 0.099, Math.PI]} />
      </group>
      <group position={[0.132, 0.44, -1.769]}>
        <mesh geometry={nodes.Object_487.geometry} material={materials.mercedes_carbon3} position={[-0.032, -0.034, -0.155]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_490.geometry} material={materials.mercedes_carbon3} position={[-0.132, 0.101, 0.039]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_493.geometry} material={materials.mercedes_carbon1} position={[0.008, 0.056, 0.358]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_496.geometry} material={materials.mercedes_carbon1} position={[-0.057, -0.132, 0.248]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_499.geometry} material={materials.mercedes_carbon3} position={[0.012, -0.063, 0.041]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_502.geometry} material={materials.mercedes_carbon3} position={[-0.066, -0.06, 0.052]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.132, 0.44, -1.769]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_506.geometry} material={materials.mercedes_carbon3} position={[-0.032, -0.034, 0.155]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_509.geometry} material={materials.mercedes_carbon3} position={[-0.132, 0.101, -0.039]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_512.geometry} material={materials.mercedes_carbon1} position={[0.008, 0.056, -0.358]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_515.geometry} material={materials.mercedes_carbon1} position={[-0.057, -0.132, -0.248]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_518.geometry} material={materials.mercedes_carbon3} position={[0.012, -0.063, -0.041]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_521.geometry} material={materials.mercedes_carbon3} position={[-0.066, -0.06, -0.052]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </group>
      <mesh geometry={nodes.Object_533.geometry} material={materials.TCAM} scale={[1.01, 1, 1]} />
      <mesh geometry={nodes.Object_536.geometry} material={materials.TCAM} scale={[1.01, 1, 1]} />
     
     <animated.group position={springs.rearWing} onClick={(e) => togglePart(e, 'Rear Wing')}
            onPointerOver={() => document.body.style.cursor = 'pointer'}
        onPointerOut={() => document.body.style.cursor = 'auto'}>
           {exploded && activePart !== 'Rear Wing' && (
             <Html position={[0, 2.2, -1.5]} center distanceFactor={8}>
               <div className="permanent-label">
                 <h4>Rear Wing</h4>
                 <p>DRS System</p>
               </div>
             </Html>
           )}
           {exploded && activePart === 'Rear Wing' && (
          <Html position={[0, 1.5, -2.8]} center distanceFactor={8}>
      <div className="annotation">
        <h4>Rear Wing</h4>
        <p>Main downforce generator featuring a hydraulic Drag Reduction System (DRS) actuator for overtaking.</p>
      </div>
    </Html>
           )}
      <group position={[-0.001, 0.636, -2.141]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_622.geometry} material={materials.mercedes_carbon3} />
        <mesh geometry={nodes.Object_625.geometry} material={materials.mercedes_paint} />
      </group>
      <mesh geometry={nodes.Object_628.geometry} material={materials.mercedes_detail} position={[0, 0.657, -1.778]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_631.geometry} material={materials.mercedes_paint_alpha} position={[-0.001, 0.637, -2.141]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_634.geometry} material={materials.mercedes_decal} position={[-0.001, 0.636, -2.145]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_637.geometry} material={materials.mercedes_decal} position={[-0.001, 0.636, -2.141]} rotation={[Math.PI / 2, 0, 0]} scale={[1.008, 1, 1]} />
      <mesh geometry={nodes.Object_640.geometry} material={materials.mercedes_decal} position={[-0.001, 0.636, -2.141]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-0.001, 0.993, -2.352]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[0, 0.045, 0.069]}>
          <mesh geometry={nodes.Object_645.geometry} material={materials.mercedes_detail} position={[0, 0.168, 0.102]} />
        </group>
        <group position={[0, 0.003, -0.009]}>
          <mesh geometry={nodes.Object_649.geometry} material={materials.mercedes_paint} />
          <mesh geometry={nodes.Object_652.geometry} material={materials.mercedes_carbon3} />
        </group>
        <mesh geometry={nodes.Object_655.geometry} material={materials.mercedes_decal} position={[0, 0.007, -0.009]} />
        <mesh geometry={nodes.Object_658.geometry} material={materials.mercedes_decal} position={[0, 0, -0.009]} />
      </group>
      
      <mesh geometry={nodes.Object_662.geometry} material={materials.mercedes_carbon1} position={[0, 0.657, -1.778]} rotation={[Math.PI / 2, 0, 0]} />
      </animated.group>
   
    </group>
  )
}

useGLTF.preload('/f1.glb.glb')
